name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy
        run: |
          curl -X POST "${{ secrets.CF_DEPLOY_HOOK }}"
